// Copyright (C) 2022  float3

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use strum_macros::Display;

// all languages listed in view-source:https://translate.google.com as of 2022-11-15
#[allow(non_camel_case_types)]
#[derive(Display, Debug, Default)]
pub enum LanguageCode {
    #[default]
    auto,
    af,
    sq,
    am,
    ar,
    hy,
    r#as,
    ay,
    az,
    bm,
    eu,
    be,
    bn,
    bho,
    bs,
    bg,
    ca,
    ceb,
    ny,
    zh_CN,
    zh_TW,
    co,
    hr,
    cs,
    da,
    dv,
    doi,
    nl,
    en,
    eo,
    et,
    ee,
    tl,
    fi,
    fr,
    fy,
    gl,
    ka,
    de,
    el,
    gn,
    gu,
    ht,
    ha,
    haw,
    iw,
    hi,
    hmn,
    hu,
    is,
    ig,
    ilo,
    id,
    ga,
    it,
    ja,
    jw,
    kn,
    kk,
    km,
    rw,
    gom,
    ko,
    kri,
    ku,
    ckb,
    ky,
    lo,
    la,
    lv,
    ln,
    lt,
    lg,
    lb,
    mk,
    mai,
    mg,
    ms,
    ml,
    mt,
    mi,
    mr,
    mni_Mtei,
    lus,
    mn,
    my,
    ne,
    no,
    or,
    om,
    ps,
    fa,
    pl,
    pt,
    pa,
    qu,
    ro,
    ru,
    sm,
    sa,
    gd,
    nso,
    sr,
    st,
    sn,
    sd,
    si,
    sk,
    sl,
    so,
    es,
    su,
    sw,
    sv,
    tg,
    ta,
    tt,
    te,
    th,
    ti,
    ts,
    tr,
    tk,
    ak,
    uk,
    ur,
    ug,
    uz,
    vi,
    cy,
    xh,
    yi,
    yo,
    zu,
}

// all languages listed in view-source:https://translate.google.com as of 2022-11-15
// pub static LANGUAGE_CODES: phf::Map<&'static str, &'static str> = phf_map! {
//     "auto" => "Detect language",
//     "af" => "Afrikaans",
//     "sq" => "Albanian",
//     "am" => "Amharic",
//     "ar" => "Arabic",
//     "hy" => "Armenian",
//     "as" => "Assamese",
//     "ay" => "Aymara",
//     "az" => "Azerbaijani",
//     "bm" => "Bambara",
//     "eu" => "Basque",
//     "be" => "Belarusian",
//     "bn" => "Bengali",
//     "bho" => "Bhojpuri",
//     "bs" => "Bosnian",
//     "bg" => "Bulgarian",
//     "ca" => "Catalan",
//     "ceb" => "Cebuano",
//     "ny" => "Chichewa",
//     "zh-CN" => "Chinese (Simplified)",
//     "zh-TW" => "Chinese (Traditional)",
//     "co" => "Corsican",
//     "hr" => "Croatian",
//     "cs" => "Czech",
//     "da" => "Danish",
//     "dv" => "Dhivehi",
//     "doi" => "Dogri",
//     "nl" => "Dutch",
//     "en" => "English",
//     "eo" => "Esperanto",
//     "et" => "Estonian",
//     "ee" => "Ewe",
//     "tl" => "Filipino",
//     "fi" => "Finnish",
//     "fr" => "French",
//     "fy" => "Frisian",
//     "gl" => "Galician",
//     "ka" => "Georgian",
//     "de" => "German",
//     "el" => "Greek",
//     "gn" => "Guarani",
//     "gu" => "Gujarati",
//     "ht" => "Haitian Creole",
//     "ha" => "Hausa",
//     "haw" => "Hawaiian",
//     "iw" => "Hebrew",
//     "hi" => "Hindi",
//     "hmn" => "Hmong",
//     "hu" => "Hungarian",
//     "is" => "Icelandic",
//     "ig" => "Igbo",
//     "ilo" => "Ilocano",
//     "id" => "Indonesian",
//     "ga" => "Irish",
//     "it" => "Italian",
//     "ja" => "Japanese",
//     "jw" => "Javanese",
//     "kn" => "Kannada",
//     "kk" => "Kazakh",
//     "km" => "Khmer",
//     "rw" => "Kinyarwanda",
//     "gom" => "Konkani",
//     "ko" => "Korean",
//     "kri" => "Krio",
//     "ku" => "Kurdish (Kurmanji)",
//     "ckb" => "Kurdish (Sorani)",
//     "ky" => "Kyrgyz",
//     "lo" => "Lao",
//     "la" => "Latin",
//     "lv" => "Latvian",
//     "ln" => "Lingala",
//     "lt" => "Lithuanian",
//     "lg" => "Luganda",
//     "lb" => "Luxembourgish",
//     "mk" => "Macedonian",
//     "mai" => "Maithili",
//     "mg" => "Malagasy",
//     "ms" => "Malay",
//     "ml" => "Malayalam",
//     "mt" => "Maltese",
//     "mi" => "Maori",
//     "mr" => "Marathi",
//     "mni-Mtei" => "Meiteilon (Manipuri)",
//     "lus" => "Mizo",
//     "mn" => "Mongolian",
//     "my" => "Myanmar (Burmese)",
//     "ne" => "Nepali",
//     "no" => "Norwegian",
//     "or" => "Odia (Oriya)",
//     "om" => "Oromo",
//     "ps" => "Pashto",
//     "fa" => "Persian",
//     "pl" => "Polish",
//     "pt" => "Portuguese",
//     "pa" => "Punjabi",
//     "qu" => "Quechua",
//     "ro" => "Romanian",
//     "ru" => "Russian",
//     "sm" => "Samoan",
//     "sa" => "Sanskrit",
//     "gd" => "Scots Gaelic",
//     "nso" => "Sepedi",
//     "sr" => "Serbian",
//     "st" => "Sesotho",
//     "sn" => "Shona",
//     "sd" => "Sindhi",
//     "si" => "Sinhala",
//     "sk" => "Slovak",
//     "sl" => "Slovenian",
//     "so" => "Somali",
//     "es" => "Spanish",
//     "su" => "Sundanese",
//     "sw" => "Swahili",
//     "sv" => "Swedish",
//     "tg" => "Tajik",
//     "ta" => "Tamil",
//     "tt" => "Tatar",
//     "te" => "Telugu",
//     "th" => "Thai",
//     "ti" => "Tigrinya",
//     "ts" => "Tsonga",
//     "tr" => "Turkish",
//     "tk" => "Turkmen",
//     "ak" => "Twi",
//     "uk" => "Ukrainian",
//     "ur" => "Urdu",
//     "ug" => "Uyghur",
//     "uz" => "Uzbek",
//     "vi" => "Vietnamese",
//     "cy" => "Welsh",
//     "xh" => "Xhosa",
//     "yi" => "Yiddish",
//     "yo" => "Yoruba",
//     "zu" => "Zulu"
// };
