// Copyright (C) 2022  float3

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// all languages listed in view-source:https://translate.google.com as of 2022-11-15
#[allow(non_camel_case_types)]
#[derive(Debug, Default)]
pub enum LanguageCode {
    #[default]
    auto,
    af,
    sq,
    am,
    ar,
    hy,
    r#as,
    ay,
    az,
    bm,
    eu,
    be,
    bn,
    bho,
    bs,
    bg,
    ca,
    ceb,
    ny,
    zh_CN,
    zh_TW,
    co,
    hr,
    cs,
    da,
    dv,
    doi,
    nl,
    en,
    eo,
    et,
    ee,
    tl,
    fi,
    fr,
    fy,
    gl,
    ka,
    de,
    el,
    gn,
    gu,
    ht,
    ha,
    haw,
    iw,
    hi,
    hmn,
    hu,
    is,
    ig,
    ilo,
    id,
    ga,
    it,
    ja,
    jw,
    kn,
    kk,
    km,
    rw,
    gom,
    ko,
    kri,
    ku,
    ckb,
    ky,
    lo,
    la,
    lv,
    ln,
    lt,
    lg,
    lb,
    mk,
    mai,
    mg,
    ms,
    ml,
    mt,
    mi,
    mr,
    mni_Mtei,
    lus,
    mn,
    my,
    ne,
    no,
    or,
    om,
    ps,
    fa,
    pl,
    pt,
    pa,
    qu,
    ro,
    ru,
    sm,
    sa,
    gd,
    nso,
    sr,
    st,
    sn,
    sd,
    si,
    sk,
    sl,
    so,
    es,
    su,
    sw,
    sv,
    tg,
    ta,
    tt,
    te,
    th,
    ti,
    ts,
    tr,
    tk,
    ak,
    uk,
    ur,
    ug,
    uz,
    vi,
    cy,
    xh,
    yi,
    yo,
    zu,
}

impl LanguageCode {
    pub fn as_str(&self) -> &str {
        match self {
            LanguageCode::auto => "auto",
            LanguageCode::af => "af",
            LanguageCode::sq => "sq",
            LanguageCode::am => "am",
            LanguageCode::ar => "ar",
            LanguageCode::hy => "hy",
            LanguageCode::r#as => "as",
            LanguageCode::ay => "ay",
            LanguageCode::az => "az",
            LanguageCode::bm => "bm",
            LanguageCode::eu => "eu",
            LanguageCode::be => "be",
            LanguageCode::bn => "bn",
            LanguageCode::bho => "bho",
            LanguageCode::bs => "bs",
            LanguageCode::bg => "bg",
            LanguageCode::ca => "ca",
            LanguageCode::ceb => "ceb",
            LanguageCode::ny => "ny",
            LanguageCode::zh_CN => "zh-CN",
            LanguageCode::zh_TW => "zh-TW",
            LanguageCode::co => "co",
            LanguageCode::hr => "hr",
            LanguageCode::cs => "cs",
            LanguageCode::da => "da",
            LanguageCode::dv => "dv",
            LanguageCode::doi => "doi",
            LanguageCode::nl => "nl",
            LanguageCode::en => "en",
            LanguageCode::eo => "eo",
            LanguageCode::et => "et",
            LanguageCode::ee => "ee",
            LanguageCode::tl => "tl",
            LanguageCode::fi => "fi",
            LanguageCode::fr => "fr",
            LanguageCode::fy => "fy",
            LanguageCode::gl => "gl",
            LanguageCode::ka => "ka",
            LanguageCode::de => "de",
            LanguageCode::el => "el",
            LanguageCode::gn => "gn",
            LanguageCode::gu => "gu",
            LanguageCode::ht => "ht",
            LanguageCode::ha => "ha",
            LanguageCode::haw => "haw",
            LanguageCode::iw => "iw",
            LanguageCode::hi => "hi",
            LanguageCode::hmn => "hmn",
            LanguageCode::hu => "hu",
            LanguageCode::is => "is",
            LanguageCode::ig => "ig",
            LanguageCode::ilo => "ilo",
            LanguageCode::id => "id",
            LanguageCode::ga => "ga",
            LanguageCode::it => "it",
            LanguageCode::ja => "ja",
            LanguageCode::jw => "jw",
            LanguageCode::kn => "kn",
            LanguageCode::kk => "kk",
            LanguageCode::km => "km",
            LanguageCode::rw => "rw",
            LanguageCode::gom => "gom",
            LanguageCode::ko => "ko",
            LanguageCode::kri => "kri",
            LanguageCode::ku => "ku",
            LanguageCode::ckb => "ckb",
            LanguageCode::ky => "ky",
            LanguageCode::lo => "lo",
            LanguageCode::la => "la",
            LanguageCode::lv => "lv",
            LanguageCode::ln => "ln",
            LanguageCode::lt => "lt",
            LanguageCode::lg => "lg",
            LanguageCode::lb => "lb",
            LanguageCode::mk => "mk",
            LanguageCode::mai => "mai",
            LanguageCode::mg => "mg",
            LanguageCode::ms => "ms",
            LanguageCode::ml => "ml",
            LanguageCode::mt => "mt",
            LanguageCode::mi => "mi",
            LanguageCode::mr => "mr",
            LanguageCode::mni_Mtei => "mni-Mtei",
            LanguageCode::lus => "lus",
            LanguageCode::mn => "mn",
            LanguageCode::my => "my",
            LanguageCode::ne => "ne",
            LanguageCode::no => "no",
            LanguageCode::or => "or",
            LanguageCode::om => "om",
            LanguageCode::ps => "ps",
            LanguageCode::fa => "fa",
            LanguageCode::pl => "pl",
            LanguageCode::pt => "pt",
            LanguageCode::pa => "pa",
            LanguageCode::qu => "qu",
            LanguageCode::ro => "ro",
            LanguageCode::ru => "ru",
            LanguageCode::sm => "sm",
            LanguageCode::sa => "sa",
            LanguageCode::gd => "gd",
            LanguageCode::nso => "nso",
            LanguageCode::sr => "sr",
            LanguageCode::st => "st",
            LanguageCode::sn => "sn",
            LanguageCode::sd => "sd",
            LanguageCode::si => "si",
            LanguageCode::sk => "sk",
            LanguageCode::sl => "sl",
            LanguageCode::so => "so",
            LanguageCode::es => "es",
            LanguageCode::su => "su",
            LanguageCode::sw => "sw",
            LanguageCode::sv => "sv",
            LanguageCode::tg => "tg",
            LanguageCode::ta => "ta",
            LanguageCode::tt => "tt",
            LanguageCode::te => "te",
            LanguageCode::th => "th",
            LanguageCode::ti => "ti",
            LanguageCode::ts => "ts",
            LanguageCode::tr => "tr",
            LanguageCode::tk => "tk",
            LanguageCode::ak => "ak",
            LanguageCode::uk => "uk",
            LanguageCode::ur => "ur",
            LanguageCode::ug => "ug",
            LanguageCode::uz => "uz",
            LanguageCode::vi => "vi",
            LanguageCode::cy => "cy",
            LanguageCode::xh => "xh",
            LanguageCode::yi => "yi",
            LanguageCode::yo => "yo",
            LanguageCode::zu => "zu",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "auto" => Some(LanguageCode::auto),
            "af" => Some(LanguageCode::af),
            "sq" => Some(LanguageCode::sq),
            "am" => Some(LanguageCode::am),
            "ar" => Some(LanguageCode::ar),
            "hy" => Some(LanguageCode::hy),
            "as" => Some(LanguageCode::r#as),
            "ay" => Some(LanguageCode::ay),
            "az" => Some(LanguageCode::az),
            "bm" => Some(LanguageCode::bm),
            "eu" => Some(LanguageCode::eu),
            "be" => Some(LanguageCode::be),
            "bn" => Some(LanguageCode::bn),
            "bho" => Some(LanguageCode::bho),
            "bs" => Some(LanguageCode::bs),
            "bg" => Some(LanguageCode::bg),
            "ca" => Some(LanguageCode::ca),
            "ceb" => Some(LanguageCode::ceb),
            "ny" => Some(LanguageCode::ny),
            "zh-CN" => Some(LanguageCode::zh_CN),
            "zh-TW" => Some(LanguageCode::zh_TW),
            "co" => Some(LanguageCode::co),
            "hr" => Some(LanguageCode::hr),
            "cs" => Some(LanguageCode::cs),
            "da" => Some(LanguageCode::da),
            "dv" => Some(LanguageCode::dv),
            "doi" => Some(LanguageCode::doi),
            "nl" => Some(LanguageCode::nl),
            "en" => Some(LanguageCode::en),
            "eo" => Some(LanguageCode::eo),
            "et" => Some(LanguageCode::et),
            "ee" => Some(LanguageCode::ee),
            "tl" => Some(LanguageCode::tl),
            "fi" => Some(LanguageCode::fi),
            "fr" => Some(LanguageCode::fr),
            "fy" => Some(LanguageCode::fy),
            "gl" => Some(LanguageCode::gl),
            "ka" => Some(LanguageCode::ka),
            "de" => Some(LanguageCode::de),
            "el" => Some(LanguageCode::el),
            "gn" => Some(LanguageCode::gn),
            "gu" => Some(LanguageCode::gu),
            "ht" => Some(LanguageCode::ht),
            "ha" => Some(LanguageCode::ha),
            "haw" => Some(LanguageCode::haw),
            "iw" => Some(LanguageCode::iw),
            "hi" => Some(LanguageCode::hi),
            "hmn" => Some(LanguageCode::hmn),
            "hu" => Some(LanguageCode::hu),
            "is" => Some(LanguageCode::is),
            "ig" => Some(LanguageCode::ig),
            "ilo" => Some(LanguageCode::ilo),
            "id" => Some(LanguageCode::id),
            "ga" => Some(LanguageCode::ga),
            "it" => Some(LanguageCode::it),
            "ja" => Some(LanguageCode::ja),
            "jw" => Some(LanguageCode::jw),
            "kn" => Some(LanguageCode::kn),
            "kk" => Some(LanguageCode::kk),
            "km" => Some(LanguageCode::km),
            "rw" => Some(LanguageCode::rw),
            "gom" => Some(LanguageCode::gom),
            "ko" => Some(LanguageCode::ko),
            "kri" => Some(LanguageCode::kri),
            "ku" => Some(LanguageCode::ku),
            "ckb" => Some(LanguageCode::ckb),
            "ky" => Some(LanguageCode::ky),
            "lo" => Some(LanguageCode::lo),
            "la" => Some(LanguageCode::la),
            "lv" => Some(LanguageCode::lv),
            "ln" => Some(LanguageCode::ln),
            "lt" => Some(LanguageCode::lt),
            "lg" => Some(LanguageCode::lg),
            "lb" => Some(LanguageCode::lb),
            "mk" => Some(LanguageCode::mk),
            "mai" => Some(LanguageCode::mai),
            "mg" => Some(LanguageCode::mg),
            "ms" => Some(LanguageCode::ms),
            "ml" => Some(LanguageCode::ml),
            "mt" => Some(LanguageCode::mt),
            "mi" => Some(LanguageCode::mi),
            "mr" => Some(LanguageCode::mr),
            "mni-Mtei" => Some(LanguageCode::mni_Mtei),
            "lus" => Some(LanguageCode::lus),
            "mn" => Some(LanguageCode::mn),
            "my" => Some(LanguageCode::my),
            "ne" => Some(LanguageCode::ne),
            "no" => Some(LanguageCode::no),
            "or" => Some(LanguageCode::or),
            "ps" => Some(LanguageCode::ps),
            "fa" => Some(LanguageCode::fa),
            "pl" => Some(LanguageCode::pl),
            "pt" => Some(LanguageCode::pt),
            "pa" => Some(LanguageCode::pa),
            "ro" => Some(LanguageCode::ro),
            "ru" => Some(LanguageCode::ru),
            "sm" => Some(LanguageCode::sm),
            "gd" => Some(LanguageCode::gd),
            "nso" => Some(LanguageCode::nso),
            "sr" => Some(LanguageCode::sr),
            "st" => Some(LanguageCode::st),
            "sn" => Some(LanguageCode::sn),
            "sd" => Some(LanguageCode::sd),
            "si" => Some(LanguageCode::si),
            "sk" => Some(LanguageCode::sk),
            "sl" => Some(LanguageCode::sl),
            "so" => Some(LanguageCode::so),
            "es" => Some(LanguageCode::es),
            "su" => Some(LanguageCode::su),
            "sw" => Some(LanguageCode::sw),
            "sv" => Some(LanguageCode::sv),
            "tg" => Some(LanguageCode::tg),
            "ta" => Some(LanguageCode::ta),
            "tt" => Some(LanguageCode::tt),
            "te" => Some(LanguageCode::te),
            "th" => Some(LanguageCode::th),
            "ti" => Some(LanguageCode::ti),
            "ts" => Some(LanguageCode::ts),
            "tr" => Some(LanguageCode::tr),
            "tk" => Some(LanguageCode::tk),
            "uk" => Some(LanguageCode::uk),
            "ur" => Some(LanguageCode::ur),
            "ug" => Some(LanguageCode::ug),
            "uz" => Some(LanguageCode::uz),
            "vi" => Some(LanguageCode::vi),
            "cy" => Some(LanguageCode::cy),
            "xh" => Some(LanguageCode::xh),
            "yi" => Some(LanguageCode::yi),
            "yo" => Some(LanguageCode::yo),
            "zu" => Some(LanguageCode::zu),
            _ => None,
        }
    }
}

// all languages listed in view-source:https://translate.google.com as of 2022-11-15
// pub static LANGUAGE_CODES: phf::Map<&'static str, &'static str> = phf_map! {
//     "auto" => "Detect language",
//     "af" => "Afrikaans",
//     "sq" => "Albanian",
//     "am" => "Amharic",
//     "ar" => "Arabic",
//     "hy" => "Armenian",
//     "as" => "Assamese",
//     "ay" => "Aymara",
//     "az" => "Azerbaijani",
//     "bm" => "Bambara",
//     "eu" => "Basque",
//     "be" => "Belarusian",
//     "bn" => "Bengali",
//     "bho" => "Bhojpuri",
//     "bs" => "Bosnian",
//     "bg" => "Bulgarian",
//     "ca" => "Catalan",
//     "ceb" => "Cebuano",
//     "ny" => "Chichewa",
//     "zh-CN" => "Chinese (Simplified)",
//     "zh-TW" => "Chinese (Traditional)",
//     "co" => "Corsican",
//     "hr" => "Croatian",
//     "cs" => "Czech",
//     "da" => "Danish",
//     "dv" => "Dhivehi",
//     "doi" => "Dogri",
//     "nl" => "Dutch",
//     "en" => "English",
//     "eo" => "Esperanto",
//     "et" => "Estonian",
//     "ee" => "Ewe",
//     "tl" => "Filipino",
//     "fi" => "Finnish",
//     "fr" => "French",
//     "fy" => "Frisian",
//     "gl" => "Galician",
//     "ka" => "Georgian",
//     "de" => "German",
//     "el" => "Greek",
//     "gn" => "Guarani",
//     "gu" => "Gujarati",
//     "ht" => "Haitian Creole",
//     "ha" => "Hausa",
//     "haw" => "Hawaiian",
//     "iw" => "Hebrew",
//     "hi" => "Hindi",
//     "hmn" => "Hmong",
//     "hu" => "Hungarian",
//     "is" => "Icelandic",
//     "ig" => "Igbo",
//     "ilo" => "Ilocano",
//     "id" => "Indonesian",
//     "ga" => "Irish",
//     "it" => "Italian",
//     "ja" => "Japanese",
//     "jw" => "Javanese",
//     "kn" => "Kannada",
//     "kk" => "Kazakh",
//     "km" => "Khmer",
//     "rw" => "Kinyarwanda",
//     "gom" => "Konkani",
//     "ko" => "Korean",
//     "kri" => "Krio",
//     "ku" => "Kurdish (Kurmanji)",
//     "ckb" => "Kurdish (Sorani)",
//     "ky" => "Kyrgyz",
//     "lo" => "Lao",
//     "la" => "Latin",
//     "lv" => "Latvian",
//     "ln" => "Lingala",
//     "lt" => "Lithuanian",
//     "lg" => "Luganda",
//     "lb" => "Luxembourgish",
//     "mk" => "Macedonian",
//     "mai" => "Maithili",
//     "mg" => "Malagasy",
//     "ms" => "Malay",
//     "ml" => "Malayalam",
//     "mt" => "Maltese",
//     "mi" => "Maori",
//     "mr" => "Marathi",
//     "mni-Mtei" => "Meiteilon (Manipuri)",
//     "lus" => "Mizo",
//     "mn" => "Mongolian",
//     "my" => "Myanmar (Burmese)",
//     "ne" => "Nepali",
//     "no" => "Norwegian",
//     "or" => "Odia (Oriya)",
//     "om" => "Oromo",
//     "ps" => "Pashto",
//     "fa" => "Persian",
//     "pl" => "Polish",
//     "pt" => "Portuguese",
//     "pa" => "Punjabi",
//     "qu" => "Quechua",
//     "ro" => "Romanian",
//     "ru" => "Russian",
//     "sm" => "Samoan",
//     "sa" => "Sanskrit",
//     "gd" => "Scots Gaelic",
//     "nso" => "Sepedi",
//     "sr" => "Serbian",
//     "st" => "Sesotho",
//     "sn" => "Shona",
//     "sd" => "Sindhi",
//     "si" => "Sinhala",
//     "sk" => "Slovak",
//     "sl" => "Slovenian",
//     "so" => "Somali",
//     "es" => "Spanish",
//     "su" => "Sundanese",
//     "sw" => "Swahili",
//     "sv" => "Swedish",
//     "tg" => "Tajik",
//     "ta" => "Tamil",
//     "tt" => "Tatar",
//     "te" => "Telugu",
//     "th" => "Thai",
//     "ti" => "Tigrinya",
//     "ts" => "Tsonga",
//     "tr" => "Turkish",
//     "tk" => "Turkmen",
//     "ak" => "Twi",
//     "uk" => "Ukrainian",
//     "ur" => "Urdu",
//     "ug" => "Uyghur",
//     "uz" => "Uzbek",
//     "vi" => "Vietnamese",
//     "cy" => "Welsh",
//     "xh" => "Xhosa",
//     "yi" => "Yiddish",
//     "yo" => "Yoruba",
//     "zu" => "Zulu"
// };
